import { Html } from "next/document";
import styles from '../styles/about.module.css';
import Head from "next/head";
import Button from "../components/button";
import Image from "next/image";
import Link from 'next/link'
import data from "../data/education.json"
import Card from '../components/Card'
import { useState } from 'react'

export default function About() {

    console.log(data);

    const [information, setInformation] = useState([...data])

    return (
        <>
            <Head>
                <title>School/about</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.header}>
                    <p>
                        <Link href="/">
                            Home
                        </Link>
                    </p>
                    <p>Continuing studies</p>
                    <p>International Students</p>
                    <p>Events and News</p>
                </div>
                <div className={styles.events}>
                    <div className={styles.eventsInfo}>
                        <Image
                            className={styles.image}
                            src="/lunar.jpg"
                            alt="image"
                            width={300}
                            height={200}
                            priority
                        />
                        <p>posted on December 20, 2022 </p>
                        <h4>Lunar new year greetings</h4>

                    </div>
                    <div className={styles.eventsInfo}>
                        <Image
                            className={styles.image}
                            src="/marketing.jpg"
                            alt="image"
                            width={300}
                            height={200}
                            priority
                        />
                        <p>posted on January 3, 2023 </p>
                        <h4>From future collge to employment</h4>

                    </div>
                    <div>
                        <div className={styles.eventsInfo}>
                            <Image
                                className={styles.image}
                                src="/award.jpg"
                                alt="image"
                                width={300}
                                height={200}
                                priority
                            />
                            <p>posted on January 10, 2023 </p>
                            <h4>Future college student awards recap</h4>
                        </div>
                    </div>
                   
                </div>
                <b> Science Degrees </b>
                    <div className={styles.degree}>
                   
                        {information && information.map((info, index) => {
                            if (info.department === "Science") {
                                return (
                                    <Card key={index} degree={info.degree} colour="" font="15px" />
                                )
                            }
                        })}
                    </div>
                <Button/>
            </main>
        </>
    )}

